apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: aistudio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # k3s default: local-path provisioner