#Requires -Version 5.1
<#
.SYNOPSIS
  Apply k3s manifests and wait for API rollout.

.PARAMETER EnvFile
  Source for secrets (default .env.deploy). Generates deploy/k3s/secret.generated.yaml (gitignored).

.EXAMPLE
  .\scripts\k3s-deploy.ps1
  .\scripts\k3s-deploy.ps1 -SkipBuild
#>
param(
  [string]$EnvFile = ".env.deploy",
  [switch]$SkipBuild,
  [string]$PublicApiUrl = ""
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot\..

if (-not (Get-Command kubectl -ErrorAction SilentlyContinue)) {
  Write-Error "kubectl not in PATH."
}

if (-not (Test-Path $EnvFile)) {
  Write-Host "Missing $EnvFile — copy from .env.deploy.example" -ForegroundColor Yellow
  exit 1
}

function Get-EnvValue($name, [string]$default = "") {
  $line = Get-Content $EnvFile | Where-Object { $_ -match "^\s*$name=" } | Select-Object -First 1
  if (-not $line) { return $default }
  $v = ($line -split "=", 2)[1].Trim()
  if (-not $v) { return $default }
  return $v
}

$jwt = Get-EnvValue "JWT_SECRET"
$enc = Get-EnvValue "FIELD_ENCRYPTION_KEY"
$pgUser = Get-EnvValue "POSTGRES_USER"
if (-not $pgUser) { $pgUser = "postgres" }
$pgPass = Get-EnvValue "POSTGRES_PASSWORD"
$pgDb = Get-EnvValue "POSTGRES_DB"
if (-not $pgDb) { $pgDb = "aistudio" }
$cors = Get-EnvValue "CORS_ORIGINS"
if (-not $cors) { $cors = "http://127.0.0.1:30080" }
$publicUrl = $PublicApiUrl
if (-not $publicUrl) { $publicUrl = Get-EnvValue "PUBLIC_API_URL" }
if (-not $publicUrl) { $publicUrl = "http://127.0.0.1:30400" }

if (-not $jwt -or -not $enc -or -not $pgPass) {
  Write-Host "JWT_SECRET, FIELD_ENCRYPTION_KEY, POSTGRES_PASSWORD required in $EnvFile" -ForegroundColor Yellow
  exit 1
}

$gen = @"
# Generated by k3s-deploy.ps1 — do not commit
apiVersion: v1
kind: Secret
metadata:
  name: aistudio-db
  namespace: aistudio
type: Opaque
stringData:
  POSTGRES_USER: $pgUser
  POSTGRES_PASSWORD: $pgPass
  POSTGRES_DB: $pgDb
---
apiVersion: v1
kind: Secret
metadata:
  name: aistudio-api
  namespace: aistudio
type: Opaque
stringData:
  JWT_SECRET: $jwt
  FIELD_ENCRYPTION_KEY: $enc
  JWT_ACCESS_TTL: "$(Get-EnvValue 'JWT_ACCESS_TTL' '15m')"
  JWT_REFRESH_TTL_DAYS: "$(Get-EnvValue 'JWT_REFRESH_TTL_DAYS' '30')"
  ORCHESTRATION_RECONCILE_ENABLED: "$(Get-EnvValue 'ORCHESTRATION_RECONCILE_ENABLED' 'false')"
  MULTICA_API_URL: "$(Get-EnvValue 'MULTICA_API_URL')"
  MULTICA_API_TOKEN: "$(Get-EnvValue 'MULTICA_API_TOKEN')"
  CORS_ORIGINS: $cors
"@

$genPath = "deploy/k3s/secret.generated.yaml"
$gen | Set-Content -Encoding utf8 $genPath

if (-not $SkipBuild) {
  & "$PSScriptRoot\k3s-build-images.ps1" -PublicApiUrl $publicUrl
  if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

kubectl apply -f deploy/k3s/namespace.yaml
kubectl apply -f $genPath
kubectl apply -f deploy/k3s/postgres-pvc.yaml
kubectl apply -f deploy/k3s/postgres.yaml
kubectl apply -f deploy/k3s/api.yaml
kubectl apply -f deploy/k3s/web.yaml

Write-Host "Waiting for api rollout..." -ForegroundColor Cyan
kubectl rollout status deployment/api -n aistudio --timeout=180s
kubectl rollout status deployment/web -n aistudio --timeout=120s

Write-Host ""
Write-Host "NodePort: API $publicUrl (port 30400)  Web http://<node>:30080" -ForegroundColor Green
Write-Host "Smoke: .\scripts\k3s-verify.ps1 -ApiUrl `"$publicUrl`"" -ForegroundColor Green